######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 7 20:49:39 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainlayout.h webcard.h
SOURCES += main.cc mainlayout.cc webcard.cc
